POST http://localhost:4000/users/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "test5@example.com",
  "password": "password123",
  "type": "pro"
}

###

POST http://localhost:4000/users/login
Content-Type: application/json

{
  "email": "test5@example.com",
  "password": "password123"
}


###
GET http://localhost:4000/users/check
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3Q1QGV4YW1wbGUuY29tIiwibmFtZSI6IkpvaG4gRG9lIiwiaWQiOiI2OTUyYjM2NzIyMGE1NzEzMjYzOTFhMTUiLCJpYXQiOjE3NjcwMzQ0NzcsImV4cCI6MTc2NzIwNzI3N30.toC62H67JD2OW3PfiihO3bhziev6ItqK5A-J2x6Ic20

###
GET http://localhost:4000/offers

###

###
POST http://localhost:4000/offers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3Q1QGV4YW1wbGUuY29tIiwibmFtZSI6IkpvaG4gRG9lIiwiaWQiOiI2OTUyYjM2NzIyMGE1NzEzMjYzOTFhMTUiLCJpYXQiOjE3NjcwMzQ0NzcsImV4cCI6MTc2NzIwNzI3N30.toC62H67JD2OW3PfiihO3bhziev6ItqK5A-J2x6Ic20

{
  "title": "Beautiful apartment in city center",
  "description": "A cozy apartment with great view...",
  "city": "Paris",
  "imageLink": "https://example.com/preview.jpg",
  "photoLinks": [
    "https://example.com/photo1.jpg",
    "https://example.com/photo2.jpg",
    "https://example.com/photo1.jpg",
    "https://example.com/photo2.jpg",
    "https://example.com/photo1.jpg",
    "https://example.com/photo2.jpg"
  ],
  "premium": false,
  "houseType": "apartment",
  "roomCount": 2,
  "guestCount": 4,
  "favourite": false,
  "rating": 4.5,
  "publishData": "2024-06-15T10:00:00.000Z",
  "rentalPrice": 15000,
  "conveniences": [
    "Breakfast",
    "Air conditioning"
  ],
  "coordinates": [
    10,
    23.456
  ],
  "authorId": "6952b367220a571326391a15"
}

###

GET http://localhost:4000/offers/6952cedaf084ccaf9ad9b069
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3Q1QGV4YW1wbGUuY29tIiwibmFtZSI6IkpvaG4gRG9lIiwiaWQiOiI2OTUyYjM2NzIyMGE1NzEzMjYzOTFhMTUiLCJpYXQiOjE3NjcwMzQ0NzcsImV4cCI6MTc2NzIwNzI3N30.toC62H67JD2OW3PfiihO3bhziev6ItqK5A-J2x6Ic20
###

PUT http://localhost:4000/offers/6952cedaf084ccaf9ad9b069
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3Q1QGV4YW1wbGUuY29tIiwibmFtZSI6IkpvaG4gRG9lIiwiaWQiOiI2OTUyYjM2NzIyMGE1NzEzMjYzOTFhMTUiLCJpYXQiOjE3NjcwMzQ0NzcsImV4cCI6MTc2NzIwNzI3N30.toC62H67JD2OW3PfiihO3bhziev6ItqK5A-J2x6Ic20

{
  "title": "Updated Beautiful apartment in city center",
  "description": "An updated cozy apartment with great view...",
  "city": "Paris",
  "imageLink": "https://example.com/updated_preview.jpg",
  "photoLinks": [
    "https://example.com/updated_photo1.jpg",
    "https://example.com/updated_photo2.jpg",
    "https://example.com/updated_photo1.jpg",
    "https://example.com/updated_photo2.jpg",
    "https://example.com/updated_photo1.jpg",
    "https://example.com/updated_photo2.jpg"
  ],
  "premium": false,
  "houseType": "apartment",
  "roomCount": 3,
  "guestCount": 5,
  "favourite": true,
  "rating": 4.8,
  "publishDate": "2024-06-20T10:00:00.000Z",
  "rentalPrice": 20000,
  "conveniences": [
    "Breakfast"
  ],
  "authorId": "6952a7d3763e0c97cd50bb2a",
  "publishData": "2024-06-20T10:00:00.000Z",
  "coordinates": [
    11,
    24.456
  ]
}

###
GET http://localhost:4000/offers/premium/Paris


###
POST http://localhost:4000/offers/6952a14fb313e39f568a631a/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3Q1QGV4YW1wbGUuY29tIiwibmFtZSI6IkpvaG4gRG9lIiwiaWQiOiI2OTUyYjM2NzIyMGE1NzEzMjYzOTFhMTUiLCJpYXQiOjE3NjcwMjc1NzUsImV4cCI6MTc2NzIwMDM3NX0.n644dAr--lD9RNYTuZzA2FPbRzBBJj9vgMh0nkrf0H0

{
  "text": "Great place to stay!",
  "userId": "6952b367220a571326391a15",
  "rating": 3
}

###
GET http://localhost:4000/offers/6952a14fb313e39f568a631a/comments

###
DELETE http://localhost:4000/offers/6952a14fb313e39f568a631a
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3Q1QGV4YW1wbGUuY29tIiwibmFtZSI6IkpvaG4gRG9lIiwiaWQiOiI2OTUyYjM2NzIyMGE1NzEzMjYzOTFhMTUiLCJpYXQiOjE3NjcwMzQ0NzcsImV4cCI6MTc2NzIwNzI3N30.toC62H67JD2OW3PfiihO3bhziev6ItqK5A-J2x6Ic20
###
GET http://localhost:4000/offers/premium/Paris
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3Q1QGV4YW1wbGUuY29tIiwibmFtZSI6IkpvaG4gRG9lIiwiaWQiOiI2OTUyYjM2NzIyMGE1NzEzMjYzOTFhMTUiLCJpYXQiOjE3NjcwMjc1NzUsImV4cCI6MTc2NzIwMDM3NX0.n644dAr--lD9RNYTuZzA2FPbRzBBJj9vgMh0nkrf0H0

###
GET http://localhost:4000/offers/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3Q1QGV4YW1wbGUuY29tIiwibmFtZSI6IkpvaG4gRG9lIiwiaWQiOiI2OTUyYjM2NzIyMGE1NzEzMjYzOTFhMTUiLCJpYXQiOjE3NjcwMzQ0NzcsImV4cCI6MTc2NzIwNzI3N30.toC62H67JD2OW3PfiihO3bhziev6ItqK5A-J2x6Ic20

###
POST http://localhost:4000/offers/favorites/6952d09cf084ccaf9ad9b0a8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3Q1QGV4YW1wbGUuY29tIiwibmFtZSI6IkpvaG4gRG9lIiwiaWQiOiI2OTUyYjM2NzIyMGE1NzEzMjYzOTFhMTUiLCJpYXQiOjE3NjcwMzQ0NzcsImV4cCI6MTc2NzIwNzI3N30.toC62H67JD2OW3PfiihO3bhziev6ItqK5A-J2x6Ic20
###

###
DELETE http://localhost:4000/offers/favorites/6952d09cf084ccaf9ad9b0a8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3Q1QGV4YW1wbGUuY29tIiwibmFtZSI6IkpvaG4gRG9lIiwiaWQiOiI2OTUyYjM2NzIyMGE1NzEzMjYzOTFhMTUiLCJpYXQiOjE3NjcwMjc1NzUsImV4cCI6MTc2NzIwMDM3NX0.n644dAr--lD9RNYTuZzA2FPbRzBBJj9vgMh0nkrf0H0
